2018-05-31 13:38:52 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(14): ZCRMModule->getRecords()
#8 {main}
2018-05-31 13:42:24 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(14): ZCRMModule->getRecords()
#8 {main}
2018-05-31 13:43:30 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(14): ZCRMModule->getRecords()
#8 {main}
2018-05-31 13:44:11 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(14): ZCRMModule->getRecords()
#8 {main}
2018-05-31 13:58:12 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(14): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:03:29 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(14): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:03:57 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:04:13 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:04:38 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:25:25 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:25:25 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:26:02 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:26:27 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:30:21 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:31:26 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:31:55 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:32:44 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:36:23 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:40:21 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:42:03 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:44:55 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:49:44 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:56:05 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:56:26 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(301): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:57:28 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:58:28 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(14): ZCRMModule->getRecords()
#8 {main}
2018-06-01 05:59:34 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:00:38 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(533): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:03:13 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(301): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:07:01 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(301): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:07:37 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(300): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:14:44 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(113): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:15:35 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(113): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:17:20 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:17:34 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:22:56 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(113): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:26:22 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:26:53 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(113): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:28:44 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:29:28 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:31:34 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:32:09 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:34:20 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:35:32 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:35:59 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(30): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:50:30 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:51:27 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:53:14 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(113): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 06:58:41 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 07:00:46 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 07:03:12 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 07:03:47 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 09:02:17 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 09:02:30 ERROR: ZCRMException Caused by:'Unknown ZCRMException' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\exception\ZCRMException.php(17)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36): ZCRMException->__construct(NULL, 302)
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 302 Fo...', 302)
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#6 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#7 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#8 {main}
2018-06-01 09:06:32 ERROR: ZCRMException Caused by:'invalid oauth scope to access this URL' in C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(36)
Trace::#0 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(29): BulkAPIResponse->handleForFaultyResponses()
#1 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\CommonAPIResponse.php(22): CommonAPIResponse->processResponse()
#2 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\response\BulkAPIResponse.php(17): CommonAPIResponse->__construct('HTTP/1.1 401 Un...', 401)
#3 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\APIRequest.php(112): BulkAPIResponse->__construct('HTTP/1.1 401 Un...', 401)
#4 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\api\handler\MassEntityAPIHandler.php(299): APIRequest->getBulkAPIResponse()
#5 C:\xampp\htdocs\Zoho\vendor\zohocrm\php-sdk\src\com\zoho\crm\library\crud\ZCRMModule.php(532): MassEntityAPIHandler->getRecords(NULL, NULL, NULL, 1, 200)
#6 C:\xampp\htdocs\Zoho\index.php(13): ZCRMModule->getRecords()
#7 {main}
